services:
  mysql:
    image: mysql:8.0
    container_name: chatting_system_db
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chatting_system_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3316:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
volumes:
  mysql-data: